### MyLibrary Configuration Settings
---

messaging:
  google_application_credentials: /home/library/credentials.json

db_conf:
  host: localhost
  user: db_user
  passwd: db_passwd
  name: db_library

dump_dir:
  path: /home/library/dump_dir

dump_ftp:
  host: localhost
  user: ftp_user
  passwd: ftp_passwd
  path: /home/library/dump_ftp